Switch to terraform for resources creation
artefactory/scheduled-pipelines pull request #1
Opened 2023-09-13 12:57 UTC by luca-serra

2023-09-15 08:48 UTC, AlexisVLRT requested changes

2023-09-15 08:48 UTC, AlexisVLRT commented on README.md
Ça serait cool d'avoir la liste des permissions requises

2023-09-15 08:48 UTC, AlexisVLRT commented on README.md
> +No particular install step is required to use this package.
On peut supprimer la section s'il n'y a rien à dire

2023-09-15 08:48 UTC, AlexisVLRT commented on README.md
> +```
Il y a peut-être moyen de rendre ça un peu plus explicite et laconique, du genre "Initialize the scheduled pipelines config file", ou un truc du genre.
Je pense que le naming du fichier doit refléter ce qu'il configure aussi, "scheduled_pipelines_config.yaml" par exemple.

2023-09-15 08:48 UTC, AlexisVLRT commented on README.md
> +   - Vertex AI API
Pas besoin des détails ici

2023-09-15 08:48 UTC, AlexisVLRT commented on config/config_example.yaml
C'est pas tout à fait le schema défini ici: https://gist.github.com/luca-serra/ba6efac22ea4a2ae36cffb0770608b57?permalink_comment_id=4688271#gistcomment-4688271

2023-09-15 08:48 UTC, AlexisVLRT commented on docs/README.md
C'est pas redondant par rapport au readme principal ça ?

2023-09-15 08:48 UTC, AlexisVLRT commented on pyproject.toml
C'est toujours nécessaire ça ?

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/cloud_function.tf
> +  name                  = "cloud-function-vertex-pipeline"
```suggestion
  name                  = "scheduled-vertex-pipeline-runner"
```

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/main.tf
> +}
Le couplage est vachement fort ici, j'aimerais bien un truc du genre `pipeline = each.value`. Tu peux sortir `cloud_function_uri` et `service_account_email` et les mettre dans les variables à part

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/modules/schedule_pipeline/variables.tf
Ajouter des valeurs pas défaut en utilisant `optional()` ici

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/outputs.tf
> +  config_files = yamldecode(file("../config/config.yaml"))
Naming pas très explicite, et sortir le loading du fichier de conf des `outputs.tf`. Je verrais ça plutôt dans le main

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/service_accounts.tf
Les display names des SA doivent être laconiques.

On peut ajouter des descriptions plus verbeuses avec ce genre de format: "Used by X to do Y" 
Par exemple: "Used by Cloud Scheduler to call the `scheduled-vertex-pipeline-runner` Cloud function"

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/service_accounts.tf
> +  role    = "roles/editor" // TODO: restrict to only the required permissions
Liste des rôles à définir dans la config de la pipeline

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/service_accounts.tf
> +  project = local.config_file.project.id
Pourquoi tu as le `project` ici et nulle part ailleurs ?

2023-09-15 08:48 UTC, AlexisVLRT commented on terraform/variables.tf
Normal que tout soit commenté ?

2023-09-15 09:12 UTC, luca-serra commented on README.md
Elles y sont dans le tableau plus bas

2023-09-15 09:13 UTC, luca-serra commented on docs/README.md
Non c'est pour l'apparition dans le doc Skaff

2023-09-15 09:14 UTC, luca-serra commented on pyproject.toml
Bien vu

2023-09-15 09:15 UTC, luca-serra commented on terraform/main.tf
> +}
Ok I see!

2023-09-15 12:51 UTC, luca-serra commented on terraform/service_accounts.tf
> +  project = local.config_file.project.id
<img width="836" alt="image" src="https://github.com/artefactory/scheduled-pipelines/assets/56681681/37fc51c4-4124-4252-838f-ab71ab1f6ddc">

2023-09-26 08:43 UTC, AlexisVLRT reviewed
En setup initial, demander à l’utilisateur d’exporter une variable d’env $PROJECT_ID et l’utiliser partout après.

----- 

Je trouve que le yaml de config est un peu caché dans son dossier. Je pense que ça peut être intéressant de le mettre à la racine et de le renommer `SCHEDULED_PIPELINES_CONFIG.yaml` pour que ça attire bien l'oeil.

« The following project values must be double quoted » -> Pas acceptable d’un point de vue UX. Là, l’utilisateur peut avoir un YAML valide qui ne va pas fonctionner. Je pense qu'utiliser `yq` à la place des regex peut aider.

Dans le YAML, réduire la charge d’onboarding de l’utilisateur en mettant des bonnes valeurs par défaut pour ces variables et en les commentant pour indiquer clairement qu’elles sont optionnelles. 

Le naming des variables peut être amélioré pour être plus clair, genre pipeline_service_account_name et scheduler_service_account_name

![image](https://github.com/artefactory/scheduled-pipelines/assets/26208387/0fb85eda-559c-48e2-9aca-ff477259a5c1)

-----

Utiliser `envsubst` pour remplacer `${BUCKET_NAME}` dans `terraform/terraform.tf` `cat terraform/terraform.tf | BUCKET_NAME=$PROJECT_ID envsubst | tee terraform/terraform.tf >/dev/null`

-----

Faire un auto-approve pour l'apply terraform

-----

La target `make build_resources` est idempotent, c’est cool. Si on peut masquer le message d’erreur qu’on a sur les déploiement subséquent, ça serait nickel. Ça éviterait que les utilisateurs se posent trop de questions.
![image](https://github.com/artefactory/scheduled-pipelines/assets/26208387/4eb26962-189a-41f2-8b41-3e66f518e82f)

-----

Je pense qu’on peut fusionner `make build_resources` et `make upload_template` en une seule target `make deploy_scheduled_pipelines`. Il y a un couplage fort entre les deux de toute manière via le nom de la pipeline. La première ne donne pas un résultat qui fonctionne pas sans la seconde. 

On pourrait à partir du yaml de config aller chercher les pipelines compilées dans un dossier spécial avec toutes les pipelines. Ça permettrait de valider que les pipelines existent bien et avoir un message d’erreur clair si elles sont pas trouvées.

-----

Il faudrait ajouter dans le readme les instructions pour redéployer après un changement de config (juste refaire le `make deploy_scheduled_pipelines`)

Ça serait aussi pratique d'avoir une section `Troubleshooting` qui donne des instruction de debug. Genre aller voir les logs de la CF quand il y a des bugs. La note qui dit le checker les logs depuis cloud scheduler est pas très pratique. Les vrais logs qui vont aider à débug sont dans la CF, pas dans le cloud scheduler.

![image](https://github.com/artefactory/scheduled-pipelines/assets/26208387/6f949af7-170f-4c88-a723-30c2b7ef1bab)

-----

Il faudrait rendre configurable les rôles du SA qui run les pipelines. Editor par défaut, configuré dans le YAML, mais modifiable

2023-10-03 08:27 UTC, AlexisVLRT approved these changes

2023-10-03 08:37 UTC, merged